// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsAouqBfK69wYLjGpRgmfsTNk78SMHsJ4',
    appId: '1:228367469843:web:743c86971732cfe6111ee6',
    messagingSenderId: '228367469843',
    projectId: 'practical-signin',
    authDomain: 'practical-signin.firebaseapp.com',
    storageBucket: 'practical-signin.firebasestorage.app',
    measurementId: 'G-4QNW570BDQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFVBxCDx-b5aS8bcwaftxA35c-ildLDDM',
    appId: '1:228367469843:android:ab9d0cef5da59a6b111ee6',
    messagingSenderId: '228367469843',
    projectId: 'practical-signin',
    storageBucket: 'practical-signin.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHTt2IJZuAJxQa8QxsCy-CGTR8_sSEYGk',
    appId: '1:228367469843:ios:202fcbe0d5880888111ee6',
    messagingSenderId: '228367469843',
    projectId: 'practical-signin',
    storageBucket: 'practical-signin.firebasestorage.app',
    iosBundleId: 'com.example.practicalSignin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHTt2IJZuAJxQa8QxsCy-CGTR8_sSEYGk',
    appId: '1:228367469843:ios:202fcbe0d5880888111ee6',
    messagingSenderId: '228367469843',
    projectId: 'practical-signin',
    storageBucket: 'practical-signin.firebasestorage.app',
    iosBundleId: 'com.example.practicalSignin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsAouqBfK69wYLjGpRgmfsTNk78SMHsJ4',
    appId: '1:228367469843:web:1606e5078648e943111ee6',
    messagingSenderId: '228367469843',
    projectId: 'practical-signin',
    authDomain: 'practical-signin.firebaseapp.com',
    storageBucket: 'practical-signin.firebasestorage.app',
    measurementId: 'G-E0RBTKYCG3',
  );

}